# Site settings
title: B站录播姬
# email: your-email@domain.com
description: >
  一个开源B站直播录制工具

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://rec.danmuji.org # the base hostname & protocol for your site
git_address: https://github.com/Bililive/rec.danmuji.org
git_edit_address: https://github.com/Bililive/rec.danmuji.org/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Asia/Shanghai
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: update

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /update/:title/
    output: true
